[package]
name = "smlog"
description = "A very basic stdout logging implementation"
version = "0.1.3"
edition = "2021"
author = "Carter J. Canedy"
license = "MIT"
repository = "https://github.com/cartercanedy/smlog"

[dependencies]
log = "0.4.22"
